### PR TITLE
connected to NewsAPI experimented with model

### PR DESCRIPTION
**Pull request by cdixson-ds**
Rubric: [ https://www.notion.so/1fc04e4fedeb429ba873b7c68d281707?v=74054da7991341c0bf970f39410c43da ]

- [ ] - Which user story does this PR fall under, why is it necessary? 
- [ ] - Commit names descriptive of changes made
- [ ] - PR scoped around a specific issue
- [ ] - Peer reviewed (reviewer checks this box after having read code / leaving review comments)
- [ ] - Remove dead code(console logs, superfluous comments) 
- [ ] - Code follows good practices (concerns kept separate as per OOP)

### Feature/Issue
[remove placeholder text and write info about PR here, user story & feature built]

### Notes
[misc details go here]

### CODE REVIEW

**Comment by BrokenShell** [comment]
The notebook looks great - good work. The only thing you should do in addition - is to remove the boilerplate template text for the rull request and replace it with a description of your work.

**Comment by ryan-hamblin** [comment]
Please provide a more thorough description of the work that was here and remove any unnecessary boilerplate in your template.

**Review by ryan-hamblin — CHANGES_REQUESTED** [review]
Please provide more description of what the changes are here. I also can't seem to pull open the changes due to the length.

**Comment by cdixson-ds** [comment]
Modified Labs28_Reddit_846 notebook and updating description

**Pull request closed without merging**
